- name: install nginx
  apt: 
    name:
      - nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600
  remote_user: jenkins
  become: yes

- name: start nginx
  service:
    name: nginx
    state: started
  remote_user: jenkins
  become: yes

- name: index
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

